name: Trigger auto deployment for container-app-ywpdgh3ngo7ii

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-ywpdgh3ngo7ii-AutoDeployTrigger-ee71dcc2-7ceb-479c-b6c4-86e89c3e2f8e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPYWPDGH3NGO7II_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPYWPDGH3NGO7II_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPYWPDGH3NGO7II_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryywpdgh3ngo7ii.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPYWPDGH3NGO7II_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPYWPDGH3NGO7II_REGISTRY_PASSWORD }}
          containerAppName: container-app-ywpdgh3ngo7ii
          resourceGroup: expresssample89dcbd63
          imageToBuild: containerregistryywpdgh3ngo7ii.azurecr.io/container-app-ywpdgh3ngo7ii:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


