name: Trigger auto deployment for container-app-gpfpt27nysv56

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-gpfpt27nysv56-AutoDeployTrigger-3d4723e4-1a2b-4697-b0d5-8d21f590e0d3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGPFPT27NYSV56_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGPFPT27NYSV56_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGPFPT27NYSV56_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrygpfpt27nysv56.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPGPFPT27NYSV56_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGPFPT27NYSV56_REGISTRY_PASSWORD }}
          containerAppName: container-app-gpfpt27nysv56
          resourceGroup: expresssample89dcbc61
          imageToBuild: containerregistrygpfpt27nysv56.azurecr.io/container-app-gpfpt27nysv56:${{ github.sha }}
          


